services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root             
      POSTGRES_PASSWORD: root         
      POSTGRES_DB: shopping            
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"                    

volumes:
  postgres_data:                        